/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as AdminCatalogoRouteImport } from './routes/admin/catalogo'
import { Route as AdminHorariosRouteImport } from './routes/admin/horarios'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoRoute = AdminCatalogoRouteImport.update({
  id: '/admin/catalogo',
  path: '/admin/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHorariosRoute = AdminHorariosRouteImport.update({
  id: '/admin/horarios',
  path: '/admin/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/pedido': typeof PedidoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/pedido': typeof PedidoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/pedido': typeof PedidoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/contato'
    | '/galeria'
    | '/meus-pedidos'
    | '/pedido'
    | '/produtos'
    | '/servicos'
    | '/admin/catalogo'
    | '/admin/horarios'
    | '/admin/pedidos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/contato'
    | '/galeria'
    | '/meus-pedidos'
    | '/pedido'
    | '/produtos'
    | '/servicos'
    | '/admin/catalogo'
    | '/admin/horarios'
    | '/admin/pedidos'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/contato'
    | '/galeria'
    | '/meus-pedidos'
    | '/pedido'
    | '/produtos'
    | '/servicos'
    | '/admin/catalogo'
    | '/admin/horarios'
    | '/admin/pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  ContatoRoute: typeof ContatoRoute
  GaleriaRoute: typeof GaleriaRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  PedidoRoute: typeof PedidoRoute
  ProdutosRoute: typeof ProdutosRoute
  ServicosRoute: typeof ServicosRoute
  AdminCatalogoRoute: typeof AdminCatalogoRoute
  AdminHorariosRoute: typeof AdminHorariosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogo': {
      id: '/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/horarios': {
      id: '/admin/horarios'
      path: '/admin/horarios'
      fullPath: '/admin/horarios'
      preLoaderRoute: typeof AdminHorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  ContatoRoute: ContatoRoute,
  GaleriaRoute: GaleriaRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  PedidoRoute: PedidoRoute,
  ProdutosRoute: ProdutosRoute,
  ServicosRoute: ServicosRoute,
  AdminCatalogoRoute: AdminCatalogoRoute,
  AdminHorariosRoute: AdminHorariosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
